apiVersion: apps/v1
kind: Deployment
metadata:
  name: cu-events-bot
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
spec:
  selector:
    matchLabels:
      server: cu-events-bot
  replicas: 1
  template:
    metadata:
      labels:
        server: cu-events-bot
    spec:
      containers:
      - name: game-container
        image: kroune/cu-events-bot:main
        imagePullPolicy: "Always"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/cu-events-bot/
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
      volumes:
        - name: config-volume
          configMap:
            name: cu-events-bot-config.json
