name: Builds docker image and pushes it

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Create example config
      run: |
        sudo mkdir /etc/game-server/
        sudo chmod -R ugo+rws /etc/game-server/
        mv .github/workflows/test-config.json /etc/game-server/config.json
    - name: Run tests
      run: gradle test --rerun-tasks
    - name: Build jar
      run: gradle build
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: kroune/cu-events-bot
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
