name: Jar file builder

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Create example config
      run: |
        sudo mkdir /etc/cu-events-bot/
        sudo chmod -R ugo+rws /etc/cu-events-bot/
        mv .github/workflows/test-config.json /etc/cu-events-bot/config.json
    - name: Run tests
      run: gradle test --rerun-tasks
    - name: Build jar
      run: gradle build
    - name: Upload jar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/cu-all.jar
